name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      # Specification
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: ^1.26
        id: go

      - name: Build the spec
        run: make build

      # speccheck
      - name: Run speccheck
        run: make test

      # check test filling
      - name: Fill tests
        working-directory: ./tools
        run: make fill

      - name: Fail if any files are untracked or have changes
        # geth outputs non-deterministic responses for two tests-
        # specifically storageKeys arrays in the responses.
        # Filter them from the diff check until fixed.
        run: >
          git status --porcelain
          ':!tests/eth_createAccessList/create-al-contract.io'
          ':!tests/eth_createAccessList/create-al-contract-eip1559.io'

  lint-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ^1.24
        id: go
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Lint tools
        working-directory: ./tools
        run: make lint
